### PR TITLE
Port UART updates to rp235x-hal

### PR DESCRIPTION
**Pull request by jannic**
The updates from #798, #837 and #838 were only applied to rp2040-hal. This patch ports them to rp235x-hal.

### CODE REVIEW

**Comment by thejpster** [comment]
What testing has been done? Should I run a demo and try it?

**Comment by jannic** [comment]
Only tested that it still builds. It seems like we don't have on-target tests for UART yet.
I'd consider the port to rp235x relatively low-risk as the changes don't touch any low-level details. But of course, doing some actual testing would be very welcome!

**Comment by thejpster** [comment]
I think we should write a loop back test that sends bytes with good and bad parity, just to check this is working as expected.

**Comment by thejpster** [comment]
I wrote a UART loopback program, and fixed some issues I observed: https://github.com/rp-rs/rp-hal/commit/1f6251a418cb8b105a39e3e491352d3be1073cb5

You can cherry-pick that here if you like it.

**Comment by jannic** [comment]
> I wrote a UART loopback program, and fixed some issues I observed: [1f6251a](https://github.com/rp-rs/rp-hal/commit/1f6251a418cb8b105a39e3e491352d3be1073cb5)
> 
> You can cherry-pick that here if you like it.

Thanks!
Did you use external pull-ups? The uart_loopback example didn't work for me. Took me a while to find out what's going on because without defmt I didn't see the unwrap failing. The fix was enabling the internal pull-ups on the RX pins.
(Only tested on rp2040 yet)

**Comment by thejpster** [comment]
No I didn't. Just a DuPont wire on a Pimoroni Pico 2 Plus.

**Comment by jannic** [comment]
Interesting. I reproducibly got a break error on rp2040 before I activated the pull-ups.

**Comment by thejpster** [comment]
🤷

**Review by 9names — APPROVED** [review]

**Pull request merged**
