### PR TITLE
Remove pico_i2c_pio example

### PR DESCRIPTION
**Pull request by jannic**
Two reasons:
- it depends on an unreleased version of i2c-pico
- i2c-pico depends on rp2040-hal = "0.6.0"

The latter causes a circular dependency between the git repos rp-hal and i2c-pico. This makes updating version numbers more difficult: It requires incremental updates, first updating the version of rp2040-hal, then updating i2c-pico to use the newer hal version, and only then updating the board support crates and their examples.

This could be reconsidered once we move the BSPs into separate repositories, https://github.com/rp-rs/rp-hal/issues/244.

### CODE REVIEW

**Comment by thejpster** [comment]
I'm in favour of this. It can always come back later.

**Comment by jannic** [comment]
> This was discussed in the past and IIRC we have a related PR to add the example in the i2c-pio repo.

Correct! I had a quick look at the repo, but didn't notice the open PR. https://github.com/rp-rs/i2c-pio-rs/pull/6

**Comment by jannic** [comment]
This would be superseded by https://github.com/rp-rs/rp-hal/pull/517 in case the BSP move gets approved.

**Comment by jannic** [comment]
#517 was merged, so this PR is obsolete

**Pull request closed without merging**
