### PR TITLE
Make BSPs provide boot2 as a default feature

### LINKED ISSUE #145: BSPs should handle rp2040_boot2
We're currently manually specifying which boot2 to use inside user/example code.
If the BSP exported a bootloader symbol, BSP examples could be generic.
Example
```rust
// alias for the bsp so we don't have to change as much code when changing targets
use feather_rp2040 as target_bsp;
#[link_section = ".boot2"]
#[used]
pub static BOOT2: [u8; 256] = target_bsp::BOOT_LOADER;
```
instead of a different
```rust
pub static BOOT2: [u8; 256] = rp2040_boot2::BOOT_LOADER_GD25Q64CS;
```
for each board

### PR DESCRIPTION
**Pull request by 9names**
Provide definition for `BOOT2` inside of each BSP hidden behind the `boot2` feature flag, and make `boot2` a default feature of the BSPs
This moves
```rust
#[cfg(feature = "boot2")]
#[link_section = ".boot2"]
#[used]
pub static BOOT2: [u8; 256] = rp2040_boot2::BOOT_LOADER_W25Q080;
```
from the BSP examples into the BSP library.
Users of the BSP then have one less thing to paste/change in their own code.

While I was already changing this code I also updated the HAL and all BSP crates to use the latest git commit for rp2040-boot2.

Closes #145

Might be worth merging https://github.com/rp-rs/rp2040-boot2-rs/pull/11 first, then doing a release of rp2040-boot2.
After updating to use the crates.io version of rp2040-boot2  we could also deal with #92 in this PR.

### CODE REVIEW

**Comment by jonathanpallant** [comment]
When would you not want your BSP to provide your bootloader?

**Comment by 9names** [comment]
So: the code in this PR works if you're using it from another crate - I developed it using https://github.com/rp-rs/rp2040-project-template).
If you're building from within rp-hal (to build the examples) none of the binaries end with boot2 linked in.
I'm unsure if this is a linker issue, a feature selection issue, or something else.

**Comment by jannic** [comment]
Looks like a linker issue: If I add `EXTERN(BOOT2)` to the linker script (and `#[no_mangle]` to the the definition), boot2 gets linked in.
Not sure why the `KEEP` isn't sufficient. Linker scripts are black magic.

**Comment by thejpster** [comment]
Can you update the PR with that change? Then this is good to go?

**Comment by jannic** [comment]
I didn't further investigate if the approach has other issues. My comment was mainly meant to point out that it's the linker who throws out the symbol, not the rust compiler or anything else.
Just adding `#[no_mangle]` to the `BOOT2` symbol is probably not a good idea anyhow, because it may collide with user-defined symbols.

**Comment by 9names** [comment]
> because it may collide with user-defined symbols.

It shouldn't collide unless a user has a no-mangle symbol (static/function) that has the same name, which I don't *think* is incredibly likely. In that instance it will be a linker error, which while painful to look at, is better than the silent failure we were getting with the previous implementation.
I renamed the unmangled symbol to BOOT2_FIRMWARE so there's no aliasing between the region name and the symbol in the linker file. This would also reduce the chance that someone will alias it accidentally.
I've left the HAL examples alone for now, so they still have mangled names but still get linked correctly.

I nearly missed fixing up the adafruit_macropad BSP because it has no examples - we should add something there because otherwise we will break it and not notice.

> Then this is good to go?
I had tested jannic's fix built correctly, but had not yet confirmed that it actually put the bootloader code into the final binary (only that nm reported something of size 100 at the correct address.

**Comment by 9names** [comment]
I guess it's worth mentioning that people will need to update the memory.x in their project to get boot2 included this way.
That does mean that it's not a breaking change (since everyone's existing boot2 include + memory.x is unaffected).

Here's my in-project link validation 2-liner

```
cargo build && cargo build --release && cargo build --examples && cargo build --release --examples
find target/thumbv6m-none-eabi/{release,debug}/examples/ -type f ! -name "*.*" -exec echo is BOOT2 in {}: \; -exec nm {} --print-size \; |grep BOOT2
```

<details>
<summary>nm output</summary>

```
ls BOOT2 in target/thumbv6m-none-eabi/release/examples/pio_proc_blink-c11649c3d3f46bbf:
10000000 00000100 r _ZN14pio_proc_blink5BOOT217h36e630702267343bE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/blinky:
10000000 00000100 r _ZN6blinky5BOOT217h210a44d66f9b57a2E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pro_micro_rainbow-65ece0eba0d18386:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/itsy_bitsy_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/spi-de8f969ad1254bd0:
10000000 00000100 r _ZN3spi5BOOT217h4641e430a17a5c7eE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/gpio_in_out-bcdb2259e9f5bbb8:
10000000 00000100 r _ZN11gpio_in_out5BOOT217h027818df3f848a3fE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pwm_blink:
10000000 00000100 r _ZN9pwm_blink5BOOT217hae1fa9de9d6e2dc7E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/feather_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/watchdog-c899e0daa7c3954a:
10000000 00000100 r _ZN8watchdog5BOOT217h1cd2999ece10ed68E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/qt_py_rainbow-7d490efb9b6ddf99:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_usb_serial_interrupt-bc68e81c8cb53348:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/itsy_bitsy_blinky-3f65f17db4588ee1:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_blinky-d7de7958574f771e:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/lcd_display-5e35590ac21c54e1:
10000000 00000100 r _ZN11lcd_display5BOOT217h6e18dbd2ce1e9a6cE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_pwm_blink:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_usb_serial_interrupt:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/feather_neopixel_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/adc:
10000000 00000100 r _ZN3adc5BOOT217h1c84c29151cb638dE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/feather_neopixel_rainbow-80333921cfc02052:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/feather_blinky-c13301832fedc3d3:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_usb_serial:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_lipo_16mb_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_i2c_pio:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pwm_blink-5a7d723a274a526e:
10000000 00000100 r _ZN9pwm_blink5BOOT217hae1fa9de9d6e2dc7E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/rom_funcs:
10000000 00000100 r _ZN9rom_funcs5BOOT217h5849cd94ef073c78E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/rom_funcs-cde338db540fafc9:
10000000 00000100 r _ZN9rom_funcs5BOOT217h5849cd94ef073c78E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_gpio_in_out-06211d80445ce0c2:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/itsy_bitsy_rainbow-a999a12cd76f7055:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/blinky-c1a1e399fe28cc78:
10000000 00000100 r _ZN6blinky5BOOT217h210a44d66f9b57a2E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_pwm_blink-5455dbed4b101f63:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/qt_py_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pio_proc_blink:
10000000 00000100 r _ZN14pio_proc_blink5BOOT217h36e630702267343bE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/watchdog:
10000000 00000100 r _ZN8watchdog5BOOT217h1cd2999ece10ed68E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_explorer_showcase-2dadec75ac4db3d9:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/spi:
10000000 00000100 r _ZN3spi5BOOT217h4641e430a17a5c7eE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_usb_twitchy_mouse:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_i2c_pio-05774bc9d8c8a8fd:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_explorer_showcase:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pio_blink:
10000000 00000100 r _ZN9pio_blink5BOOT217h085c851902df7cd8E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/itsy_bitsy_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_lipo_16mb_blinky-8907577e3d39f525:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_usb_serial-7ae2c5fdba372ab3:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/gpio_in_out:
10000000 00000100 r _ZN11gpio_in_out5BOOT217h027818df3f848a3fE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_rtic:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/adc-982003bfd24cead7:
10000000 00000100 r _ZN3adc5BOOT217h1c84c29151cb638dE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_usb_twitchy_mouse-a0ea85eb91dc49bc:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/i2c:
10000000 00000100 r _ZN3i2c5BOOT217h1bcfe7c6dc73e171E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/lcd_display:
10000000 00000100 r _ZN11lcd_display5BOOT217h6e18dbd2ce1e9a6cE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/i2c-eec5f1fde714dc41:
10000000 00000100 r _ZN3i2c5BOOT217h1bcfe7c6dc73e171E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_countdown_blinky-2c29dcfdb7daac07:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/uart:
10000000 00000100 r _ZN4uart5BOOT217hace540ea5dd8110cE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pio_blink-f61cb586c6e84658:
10000000 00000100 r _ZN9pio_blink5BOOT217h085c851902df7cd8E
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pro_micro_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_gpio_in_out:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_rtic-237e939fd578e0b9:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/pico_countdown_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/release/examples/uart-47fb47564b0f895b:
10000000 00000100 r _ZN4uart5BOOT217hace540ea5dd8110cE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pio_blink-8bb5379b6c825ca5:
10000000 00000100 r _ZN9pio_blink5BOOT217h865e8392ba402649E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/blinky:
10000000 00000100 r _ZN6blinky5BOOT217h92266f0787df457fE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/blinky-9fd7c0bd2b14aab9:
10000000 00000100 r _ZN6blinky5BOOT217h92266f0787df457fE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/itsy_bitsy_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pwm_blink-b2bb78f48df63877:
10000000 00000100 r _ZN9pwm_blink5BOOT217h85a61c81287a2357E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_blinky-e6ee919e3057a37a:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pwm_blink:
10000000 00000100 r _ZN9pwm_blink5BOOT217h85a61c81287a2357E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/feather_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_rtic-2c257cefcfd4e6d9:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/uart-cb8e7e44173de7f4:
10000000 00000100 r _ZN4uart5BOOT217h9a916141d88b4182E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/i2c-a40e0d9f080d2938:
10000000 00000100 r _ZN3i2c5BOOT217h3f52b55b0618da77E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/rom_funcs-7e2201d0ba31f381:
10000000 00000100 r _ZN9rom_funcs5BOOT217hbfc31973bbe39062E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_pwm_blink:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_usb_serial_interrupt:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/feather_neopixel_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_pwm_blink-cfc331391f37767f:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/adc:
10000000 00000100 r _ZN3adc5BOOT217h03c0d69284c07a49E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_usb_serial:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_lipo_16mb_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_i2c_pio:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/rom_funcs:
10000000 00000100 r _ZN9rom_funcs5BOOT217hbfc31973bbe39062E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/itsy_bitsy_rainbow-40c2d8aded4cfb4c:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/feather_blinky-77fe5bfa10d7cf11:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/qt_py_rainbow-f1fd87b939f15491:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_explorer_showcase-1c7c0821d5cb8e36:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/gpio_in_out-f5f3fcc10fc9c12e:
10000000 00000100 r _ZN11gpio_in_out5BOOT217h66ca21be6eff68fdE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/feather_neopixel_rainbow-0ebaed3fc08e227b:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/qt_py_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_usb_twitchy_mouse-459d23668a66bdb4:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pio_proc_blink:
10000000 00000100 r _ZN14pio_proc_blink5BOOT217hcf581886aac85b7bE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/watchdog:
10000000 00000100 r _ZN8watchdog5BOOT217h877a759b84141be9E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/spi:
10000000 00000100 r _ZN3spi5BOOT217h739676a7384e9232E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_usb_twitchy_mouse:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_explorer_showcase:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pio_blink:
10000000 00000100 r _ZN9pio_blink5BOOT217h865e8392ba402649E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/itsy_bitsy_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/adc-4fd5b02f0bcc7fc7:
10000000 00000100 r _ZN3adc5BOOT217h03c0d69284c07a49E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/lcd_display-c84f7b6f86b3642e:
10000000 00000100 r _ZN11lcd_display5BOOT217h383c3aa949ccba89E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/gpio_in_out:
10000000 00000100 r _ZN11gpio_in_out5BOOT217h66ca21be6eff68fdE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/watchdog-632534ed43fdee12:
10000000 00000100 r _ZN8watchdog5BOOT217h877a759b84141be9E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_rtic:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_countdown_blinky-9bdb9ac9bb129815:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pio_proc_blink-b1c9f2fe55c3dc3c:
10000000 00000100 r _ZN14pio_proc_blink5BOOT217hcf581886aac85b7bE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/spi-0ad723e2d56b253d:
10000000 00000100 r _ZN3spi5BOOT217h739676a7384e9232E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pro_micro_rainbow-945c9f3476b4e256:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/i2c:
10000000 00000100 r _ZN3i2c5BOOT217h3f52b55b0618da77E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_usb_serial_interrupt-f84d6838ade221f3:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_usb_serial-cba77452f2c12b3c:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/lcd_display:
10000000 00000100 r _ZN11lcd_display5BOOT217h383c3aa949ccba89E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/uart:
10000000 00000100 r _ZN4uart5BOOT217h9a916141d88b4182E
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_lipo_16mb_blinky-6d083bf3938ee522:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pro_micro_rainbow:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_gpio_in_out:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_i2c_pio-d090cd806f3c4646:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_countdown_blinky:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/pico_gpio_in_out-7e57ff3a548f3e55:
10000000 00000100 R BOOT2_FIRMWARE
is BOOT2 in target/thumbv6m-none-eabi/debug/examples/itsy_bitsy_blinky-0e7c8f05b8817ef1:
10000000 00000100 R BOOT2_FIRMWARE
```

</details>

And my validation for including a BSP with boot2 from an external project

<details>

<summary>objdump output when calling from external project</summary>

```
cargo objdump -- --disassemble --section .boot2
    Finished dev [optimized + debuginfo] target(s) in 0.02s

rp2040-project-template:        file format elf32-littlearm

Disassembly of section .boot2:

10000000 <BOOT2_FIRMWARE>:
10000000: 00 b5         push    {lr}
10000002: 32 4b         ldr     r3, [pc, #200] <BOOT2_FIRMWARE+0xce>
10000004: 21 20         movs    r0, #33
10000006: 58 60         str     r0, [r3, #4]
10000008: 98 68         ldr     r0, [r3, #8]
1000000a: 02 21         movs    r1, #2
1000000c: 88 43         bics    r0, r1
1000000e: 98 60         str     r0, [r3, #8]
10000010: d8 60         str     r0, [r3, #12]
10000012: 18 61         str     r0, [r3, #16]
10000014: 58 61         str     r0, [r3, #20]
10000016: 2e 4b         ldr     r3, [pc, #184] <BOOT2_FIRMWARE+0xd2>
10000018: 00 21         movs    r1, #0
1000001a: 99 60         str     r1, [r3, #8]
1000001c: 04 21         movs    r1, #4
1000001e: 59 61         str     r1, [r3, #20]
10000020: 01 21         movs    r1, #1
10000022: f0 22         movs    r2, #240
10000024: 99 50         str     r1, [r3, r2]
10000026: 2b 49         ldr     r1, [pc, #172] <BOOT2_FIRMWARE+0xd6>
10000028: 19 60         str     r1, [r3]
1000002a: 01 21         movs    r1, #1
1000002c: 99 60         str     r1, [r3, #8]
1000002e: 35 20         movs    r0, #53
10000030: 00 f0 44 f8   bl      0x100000bc <BOOT2_FIRMWARE+0xbc> @ imm = #136
10000034: 02 22         movs    r2, #2
10000036: 90 42         cmp     r0, r2
10000038: 14 d0         beq     0x10000064 <BOOT2_FIRMWARE+0x64> @ imm = #40
1000003a: 06 21         movs    r1, #6
1000003c: 19 66         str     r1, [r3, #96]
1000003e: 00 f0 34 f8   bl      0x100000aa <BOOT2_FIRMWARE+0xaa> @ imm = #104
10000042: 19 6e         ldr     r1, [r3, #96]
10000044: 01 21         movs    r1, #1
10000046: 19 66         str     r1, [r3, #96]
10000048: 00 20         movs    r0, #0
1000004a: 18 66         str     r0, [r3, #96]
1000004c: 1a 66         str     r2, [r3, #96]
1000004e: 00 f0 2c f8   bl      0x100000aa <BOOT2_FIRMWARE+0xaa> @ imm = #88
10000052: 19 6e         ldr     r1, [r3, #96]
10000054: 19 6e         ldr     r1, [r3, #96]
10000056: 19 6e         ldr     r1, [r3, #96]
10000058: 05 20         movs    r0, #5
1000005a: 00 f0 2f f8   bl      0x100000bc <BOOT2_FIRMWARE+0xbc> @ imm = #94
1000005e: 01 21         movs    r1, #1
10000060: 08 42         tst     r0, r1
10000062: f9 d1         bne     0x10000058 <BOOT2_FIRMWARE+0x58> @ imm = #-14
10000064: 00 21         movs    r1, #0
10000066: 99 60         str     r1, [r3, #8]
10000068: 1b 49         ldr     r1, [pc, #108] <BOOT2_FIRMWARE+0xd8>
1000006a: 19 60         str     r1, [r3]
1000006c: 00 21         movs    r1, #0
1000006e: 59 60         str     r1, [r3, #4]
10000070: 1a 49         ldr     r1, [pc, #104] <BOOT2_FIRMWARE+0xdc>
10000072: 1b 48         ldr     r0, [pc, #108] <BOOT2_FIRMWARE+0xe2>
10000074: 01 60         str     r1, [r0]
10000076: 01 21         movs    r1, #1
10000078: 99 60         str     r1, [r3, #8]
1000007a: eb 21         movs    r1, #235
1000007c: 19 66         str     r1, [r3, #96]
1000007e: a0 21         movs    r1, #160
10000080: 19 66         str     r1, [r3, #96]
10000082: 00 f0 12 f8   bl      0x100000aa <BOOT2_FIRMWARE+0xaa> @ imm = #36
10000086: 00 21         movs    r1, #0
10000088: 99 60         str     r1, [r3, #8]
1000008a: 16 49         ldr     r1, [pc, #88] <BOOT2_FIRMWARE+0xe6>
1000008c: 14 48         ldr     r0, [pc, #80] <BOOT2_FIRMWARE+0xe0>
1000008e: 01 60         str     r1, [r0]
10000090: 01 21         movs    r1, #1
10000092: 99 60         str     r1, [r3, #8]
10000094: 01 bc         pop     {r0}
10000096: 00 28         cmp     r0, #0
10000098: 00 d0         beq     0x1000009c <BOOT2_FIRMWARE+0x9c> @ imm = #0
1000009a: 00 47         bx      r0
1000009c: 12 48         ldr     r0, [pc, #72] <BOOT2_FIRMWARE+0xe8>
1000009e: 13 49         ldr     r1, [pc, #76] <BOOT2_FIRMWARE+0xee>
100000a0: 08 60         str     r0, [r1]
100000a2: 03 c8         ldm     r0, {r0, r1}
100000a4: 80 f3 08 88   msr     msp, r0
100000a8: 08 47         bx      r1
100000aa: 03 b5         push    {r0, r1, lr}
100000ac: 99 6a         ldr     r1, [r3, #40]
100000ae: 04 20         movs    r0, #4
100000b0: 01 42         tst     r1, r0
100000b2: fb d0         beq     0x100000ac <BOOT2_FIRMWARE+0xac> @ imm = #-10
100000b4: 01 20         movs    r0, #1
100000b6: 01 42         tst     r1, r0
100000b8: f8 d1         bne     0x100000ac <BOOT2_FIRMWARE+0xac> @ imm = #-16
100000ba: 03 bd         pop     {r0, r1, pc}
100000bc: 02 b5         push    {r1, lr}
100000be: 18 66         str     r0, [r3, #96]
100000c0: 18 66         str     r0, [r3, #96]
100000c2: ff f7 f2 ff   bl      0x100000aa <BOOT2_FIRMWARE+0xaa> @ imm = #-28
100000c6: 18 6e         ldr     r0, [r3, #96]
100000c8: 18 6e         ldr     r0, [r3, #96]
100000ca: 02 bd         pop     {r1, pc}
100000cc: 00 00         movs    r0, r0
100000ce: 02 40         ands    r2, r0
100000d0: 00 00         movs    r0, r0
100000d2: 00 18         adds    r0, r0, r0
100000d4: 00 00         movs    r0, r0
100000d6: 07 00         movs    r7, r0
100000d8: 00 03         lsls    r0, r0, #12
100000da: 5f 00         lsls    r7, r3, #1
100000dc: 21 22         movs    r2, #33
100000de: 00 00         movs    r0, r0
100000e0: f4 00         lsls    r4, r6, #3
100000e2: 00 18         adds    r0, r0, r0
100000e4: 22 20         movs    r0, #34
100000e6: 00 a0         adr     r0, #0 <BOOT2_FIRMWARE+0xea>
100000e8: 00 01         lsls    r0, r0, #4
100000ea: 00 10         asrs    r0, r0, #32
100000ec: 08            <unknown>
100000ed: ed 00         lsls    r5, r5, #3
100000ef: e0 00         lsls    r0, r4, #3
                ...
100000f9: 00 00         movs    r0, r0
100000fb: 00 07         lsls    r0, r0, #28
100000fd: 0b 8f         ldrh    r3, [r1, #56]
100000ff: d5            <unknown>
```

</details>

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Does the linker script in quick start need updating too?

**Pull request merged**
