### PR TITLE
Add debug derive for the GPIO structures

### PR DESCRIPTION
**Pull request by robamu**
Is there a general problem adding these derives to more structures? I am trying to use a driver for a LCD display, and I can not unwrap the returned result structure because Debug is not implemented by the pin structures used by the driver. This applies to both the concrete pins and the downgraded pins.

These were only the derives I needed to pass both dyn pins and concrete pins to the driver. There are probably a lot more structures where t his derive could be added.

### CODE REVIEW

**Comment by jannic** [comment]
CI failed due to a new warning in rustc 1.82.0.
Fixed in https://github.com/rp-rs/rp-hal/pull/863.

**Comment by thejpster** [comment]
@robamu can you rebase?

**Comment by robamu** [comment]
I can do that

**Comment by thejpster** [comment]
This PR picked up a lot of unrelated commits. Maybe we can fix it by doing a rebase when we merge. The diff itself looks fine.

**Comment by jannic** [comment]
I think the pull request looks a bit strange because @robamu merged with main instead of rebasing. Git should handle that fine. Worst case the history will have a few unnecessary branch points, but yes, "rebase and merge" should avoid even that.

**Review by jannic — APPROVED** [review]

**Pull request merged**
