### PR TITLE
remove unused dependencies & add GHA flow

### PR DESCRIPTION
**Pull request by ithinuel**
Should it be made part of the existing jobs or parallel ones?

### CODE REVIEW

**Comment by ithinuel** [comment]
Either way, it make the checks much much longer, so I'm not sure it's entirely worth it to have it as workflow.
We might just be good having it run manually every now and then.

**Review by 9names — APPROVED** [review]
Glad to drop all the unused deps.
Looks like all the extra time is just building cargo-udeps.
I couldn't manage to get toolchain caching working correctly, but it should be possible to do this once and cache it for subsequent runs...

**Comment by ithinuel** [comment]
Seems like the `use-tool-cache` option is deprecated ( https://github.com/actions-rs/tool-cache/ is archived )
And support using `@action/cache` has been waiting for about 2years: https://github.com/actions-rs/core/pull/125 and https://github.com/actions-rs/install/pull/5

**Comment by 9names** [comment]
Ah. Maybe using a prebuilt version instead? There are binary releases on github (need to untar them though).
I'll check how fast that is...

**Comment by 9names** [comment]
takes 1.5 seconds on my machine.
wish i didn't have to encode the version number in the string, maybe we could regex it out somehow but it might be more cursed...

```system
wget -q -O - https://github.com/est31/cargo-udeps/releases/download/v0.1.32/cargo-udeps-v0.1.32-x86_64-unknown-linux-gnu.tar.gz | tar -xz && mv ./cargo-udeps-v0.1.32-x86_64-unknown-linux-gnu/cargo-udeps ~/.cargo/bin && rm ./cargo-udeps-v0.1.32-x86_64-unknown-linux-gnu -r
```

**Comment by ithinuel** [comment]
I found https://github.com/aig787/cargo-udeps-action :D seems to work as expected

**Pull request merged**
