### PR TITLE
Use new spinlock API provide by PAC 0.3.0

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Review by 9names — APPROVED** [review]
LGTM

**Comment by thejpster** [comment]
Now with const generic spinlocks.

**Comment by thejpster** [comment]
Need to consider https://github.com/rp-rs/rp-hal/issues/282 before merging, although it is at least noted.

**Comment by thejpster** [comment]
Spinlock 31 is now hidde (resolving #282)

**Review by 9names — APPROVED** [review]
No macros, nice! And good to have some documentation for this too.
I'm looking forward to testing it out.
LGTM

**Pull request merged**
