### PR TITLE
Move on-target-tests back to the work space

### PR DESCRIPTION
**Pull request by ithinuel**
- requires #761

### CODE REVIEW

**Comment by jannic** [comment]
> * requires [Bump msrv from 1.65 to 1.75 #761](https://github.com/rp-rs/rp-hal/pull/761)

Are you sure? I reverted that change and both the CI pipeline and the on-target tests still succeed.

Asides from that: @9names, you excluded the on-target-tests from the workspace in https://github.com/rp-rs/rp-hal/pull/457. As it seems like with ithinuels changes, the CI pipeline is happy with them added back to the workspace, do you think there's still some reason to keep them separate?

**Comment by 9names** [comment]
I have no reason to exclude them from the workspace

**Review by 9names — APPROVED** [review]
Changes look fine to me

**Comment by ithinuel** [comment]
@jannic requires in the sense that I'd like to avoid having to rebase the PRs, so having them merged in-order should help reduce unnecessary work.

**Comment by jannic** [comment]
> @jannic "requires" in the sense that I'd like to avoid having to rebase the PRs, so having them merged in-order should help reduce unnecessary work. (and this PR includes the changes of its preceding)

Ah ok, understand. Personally I prefer truly independent pull requests, but they of course have the risk of merge conflicts.

**Pull request merged**
