### PR TITLE
Using thread send safe UART* marker, when splitting

### PR DESCRIPTION
**Pull request by marius-meissner**
For details, see #284.

The approach was initially suggested by @danielzfranklin. I just filed the PR and did some hardware testing.
Changes were successfully tested by using UART for ESP8266 Wi-Fi offloading in combination with RTIC.

There are perhaps better ways to solve this problem, so I'm looking forward to your feedback.

### CODE REVIEW

**Comment by 9names** [comment]
Looks okay to me.
I'll point out (in case you are unaware) that ::steal() has side effects. Shouldn't be a problem here, as you will have already called ::take() before this.
https://github.com/rust-embedded/cortex-m/issues/186

Another option is to create an new token by transmuting ()
```rust
let uart_token: UART0 = unsafe { core::mem::transmute( () ) };
```

**Review by 9names — APPROVED** [review]
LGTM

**Comment by marius-meissner** [comment]
Thanks for the quick approval and the feedback.
I had unfortunately forgotten to reply to the previous comment.

> Another option is to create an new token by transmuting ()

Right. But I think in this case the use of take slightly outweighs, especially because of the following indications:

> transmute is incredibly unsafe. There are a vast number of ways to cause [undefined behavior](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html) with this function. transmute should be the absolute last resort.

**Comment by danielzfranklin** [comment]
I mostly agree.

There's nothing about transmuting `()` to an arbitrary zero-sized type that's inherently unsound, the question is only whether forging a type a library assumes only it can create lets you "trick" code that relies on something for safety[1].

Either way we're "tricking" the pac in a way we know is sound based on internal implementation details. The `steal` call is extremely cheap though, and I feel like it reads cleaner.

[1]: https://internals.rust-lang.org/t/is-synthesizing-zero-sized-values-safe/11506/5

**Pull request merged**
