### PR TITLE
Fix RealTimeClock & UsbBus ownership

### PR DESCRIPTION
**Pull request by jnthbdn**
The RealTimeClock works great, but it takes ownership of the `rtc_clock` field in the `ClockManager`, which makes it invalid (partial move).
Moreover, the `RealTimeClock` struct doesn't allow freeing `rtc_clock`, the `new` function doesn't do anything about it, so the instance is destroyed.

Following the model of other functions present in the HAL for clock configuration (such as `setup_pll_blocking` or `configure_clock` from ClockManger), I modified the parameter so that it was a reference.

#724

Thanks for this brilliant HAL!

### CODE REVIEW

**Comment by jnthbdn** [comment]
Thanks for your review, I quite agree with your comment, it would make the function's intentions clearer.

But the more I look at the code, the more I wonder if my RP is really relevant...

Let me explain, as you said in issue #724, it's interesting that ownership is taken in order to ensure that clocks are not subsequently modified. But there's still the problem of the ClockManager being partially moved. So in the end, even though it's a big change, wouldn't it be better to make the ClockManager fields `Option<T>`?
Changing this line
https://github.com/rp-rs/rp-hal/blob/cfd6c128a1688186f419e3bd60ce469ddeb7fb47/rp2040-hal/src/clocks/macros.rs#L22 with `pub [<$name:snake>]: Option<$name>`

Because in this PR we've solved the RealTimeClock problem, but the `new` function in the `UsbBus` does the same thing.
https://github.com/rp-rs/rp-hal/blob/cfd6c128a1688186f419e3bd60ce469ddeb7fb47/rp2040-hal/src/usb.rs#L441

**Comment by ithinuel** [comment]
Would it make sense to rather than having fields public, adding a `split` method and include as part of its output a extra entry offering a subset of what the clock manager does but that does not collide with the individual clocks ?

**Comment by jnthbdn** [comment]
I modified the PR by adding `free` functions to the `RealTimeClock` and `UsbBus` structs.

**Review by ithinuel — APPROVED** [review]
LGTM

**Pull request merged**
