### PR TITLE
Add embedded_hal::timer support

### PR DESCRIPTION
**Pull request by ithinuel**
This PR implements support for the [`embedded_hal::timer`](https://docs.rs/embedded-hal/0.2.6/embedded_hal/timer/index.html) traits.

### CODE REVIEW

**Comment by 9names** [comment]
Hey, thanks for this. If it's not to much could I get you to write a standalone example that uses these traits, so it's obvious for new users how the timer should be used?
Also, not sure if you saw #100 but the current implementation of get_counter could also use some small modifications.

**Comment by ithinuel** [comment]
I updated the `get_counter` function and added an example for the pico board.

I also have https://github.com/ithinuel/rp-hal/tree/add-pro-micro-ws2812-example that adds an example for the pro micro rp2040.
This example combines PIO & Timer (as CountDown trait). (also happy to move https://github.com/ithinuel/ws2812-pio-rs/ under this org)

**Review by 9names — APPROVED** [review]
LGTM

**Comment by 9names** [comment]
Not sure what we should do with regards to PIO driver crates just yet.
Might be worth discussing it in the matrix channel?

**Pull request merged**
