### PR TITLE
split rom_data into safe and unsafe functions

### PR DESCRIPTION
**Pull request by anall**
Most of the functions provided in `rom_data` can do unsafe things.

You can use `memset`/friends to modify Rust data structures without limits. It is safe Rust to get a raw (const or not) pointer to something, and it is also safe Rust to turn a `*const T` into a `*mut T`. It is only unsafe to dereference the raw pointer.

Any operations from the ROM that allow pointer operations on memory (ergo a "dereference") should be unsafe.
I believe the operations that change how the flash is set up should also be considered unsafe, as those may cause undefined behavior in the code (especially, but not only, if you are using the QSPI pins as GPIO.)

`wait_for_vector` has some preconditions for when it should be used, so should probably be unsafe as well.

I see no unsafe behavior from `popcount32`, `reverse32`, `clz32`, or `ctz32` unless there is some weird behavior in the ROM I am unaware of.

I am not sure if `reset_to_usb_boot` should be considered unsafe. I do not believe that can cause undefined behavior in the following code as it forces a reset, but I am not sure if we want to gate that behind an unsafe as an "are you sure"?

I am not sure if there's a better way to do this with the macro, as Rust macros are still not my strong point.

### CODE REVIEW

**Comment by 9names** [comment]
This looks good to me. 
I don't think we should mark things as unsafe unless they actually are. A reset is a normal part of a system lifecycle, we should assume that a user that calls it knows what they're doing.
I am also not a macro expert, so I'm not going to cast any judgement here.

**Comment by anall** [comment]
So then all I'm really not 100% sure about are the flash functions (but those can do raw memory writes, so probably should be unsafe) and `wait_for_vector` (but I believe the only "harm" that can do is lock up the processor if called on the wrong core)

The flash related functions can also mess up the QSPI-as-GPIO pin configuration if you are using that.

I think both should stay unsafe, but I am on the fence about `wait_for_vector`

**Comment by 9names** [comment]
My feeling: flash funcs are unsafe for the reasons you've stated.
wait_for_vector is technically safe as far as I'm concerned, but I'm also on the fence about whether it's worth moving it into the safe funcs list. I don't think it's something we should spend too much thought on - it's likely to only be called once at startup.
Maybe we should wait until we try using it before deciding where to put it?

**Comment by anall** [comment]
>I don't think it's something we should spend too much thought on - it's likely to only be called once at startup.

We shouldn't even need to call it in normal operation. The bootrom calls it for us on the second core. I think the only reason we would need to call that function (on the second core) is if we want to effectively reset the second core (from the second core).

>Maybe we should wait until we try using it before deciding where to put it?

Reasonable.

**Comment by anall** [comment]
It seems that this somehow got accidentally reverted at some point. Shall I just open a new PR to un-revert it?

**Comment by 9names** [comment]
Yep, new PR please

**Pull request merged**
